[package]
name = "danubec_ast_lowering"
version = "0.1.0"
edition = "2021"

[dependencies]
danubec_hir.path = "../danubec_hir"
danubec_middle.path = "../danubec_middle"
danubec_lst.path = "../danubec_lst"
