[package]
name = "danubec-syntax-node"
version = "0.1.0"
authors = ["Danuel <public.danuel@gmail.com>"]
edition = "2021"

[dependencies]
danubec-ast = { path = "../danubec-ast" }
danubec-syntax-kind = { path = "../danubec-syntax-kind" }
rowan = "0.15.13"
