[package]
name = "danube-ast"
version = "0.1.0"
authors = ["Danuel <public.danuel@gmail.com>"]
edition = "2018"

[dependencies]
danube-token = { path = "../danube-token" }
danube-index = { path = "../danube-index" }
