[package]
name = "danubec_parse"
version = "0.1.0"
edition = "2024"

[dependencies]
danubec_data_structure.path = "../danubec_data_structure"
danubec_lex.path = "../danubec_lex"
danubec_lst.path = "../danubec_lst"
danubec_syntax.path = "../danubec_syntax"
insta.workspace = true
