[package]
name = "danubec_parse"
version = "0.1.0"
edition = "2021"

[dependencies]
danubec_lex = { path = "../danubec_lex" }
danubec_syntax = { path = "../danubec_syntax" }
insta = { workspace = true }
