[package]
name = "danubec"
version = "0.1.0"
authors = ["Danuel <public.danuel@gmail.com>"]
edition = "2021"

[dependencies]
danubec-ast = { path = "../danubec-ast" }
danubec-lex = { path = "../danubec-lex" }
danubec-parse = { path = "../danubec-parse" }
