[package]
name = "danubec"
version = "0.1.0"
edition = "2024"

[dependencies]
danubec_compile.path = "../danubec_compile"
danubec_diagnostic.path = "../danubec_diagnostic"
danubec_middle.path = "../danubec_middle"
