[package]
name = "danube-parse"
version = "0.1.0"
authors = ["Danuel <public.danuel@gmail.com>"]
edition = "2018"

[dependencies]
danube-ast = { path = "../danube-ast" }
danube-lex = { path = "../danube-lex" }
danube-token = { path = "../danube-token" }
