[package]
name = "danube-compile"
version = "0.1.0"
authors = ["Danuel <public.danuel@gmail.com>"]
edition = "2018"

[dependencies]
danube-diagnostics = { path = "../danube-diagnostics" }
danube-lex = { path = "../danube-lex" }
danube-parse = { path = "../danube-parse" }
